export const sample_foods=[
    {
        id:'1',
        name:'Biriyani',
        cookTime:'30-45',
        price: 200,
        favorite: true,
        origins:['Dindigul '],
        stars: 4.5,
        imageUrl:'food1.jpg',
        tags:['favorite food','Lunch','Biriyani'],
    },
    {
        id:'2',
        name:'Idli',
        cookTime:'10-20',
        price: 55,
        favorite: false,
        origins:['Tamilnadu'],
        stars: 4,
        imageUrl: 'food2.jpg',
        tags:['Breakfast','Dinner'],
    },
    {
        id:'3',
        name:'Full Meals',
        cookTime:'45-60',
        price:150,
        favorite: false,
        origins:['Tamilnadu'],
        stars:3.5,
        imageUrl: 'food3.jpg',
        tags:['Lunch','Veg'],
    },
    {
        id:'4',
        name:'Chapati',
        cookTime:'10-20',
        price:60,
        favorite: false,
        origins:['Chennai'],
        stars:4,
        imageUrl:'food4.jpg',
        tags:['Dinner','Breakfast'],
    },
    {
        id:'5',
        name:'Parotta',
        cookTime:'15-25',
        price:50,
        favorite: true,
        origins:['Madurai '],
        stars:4.5,
        imageUrl:'food5.jpg',
        tags:['favorite','Dinner'],
    },
    {
        id:'6',
        name:'Dosa',
        cookTime:'10-20',
        price:65,
        favorite:true,
        origins:['india'],
        stars:4.5,
        imageUrl:'food6.jpg',
        tags:['Dinner','Fast Make','Breakfast'],
    }
];

export const sample_tags=[
    {name:'All' ,count:6},
    {name: 'Breakfast',count:3},
    {name: 'Biriyani',count:1},
    {name: 'Dinner',count:4},
    {name: 'Lunch',count:2},
];